'use strict';

angular.module('myApp.services', [])

.service('PeopleService', [function() {

	this.list = [{id:1, name: "Ana", age: "17"},
				{id:2, name: "Paul", age: "45"},
				{id:3, name: "John", age: "37"},
				{id:4, name: "Jeffrey", age: "27"},
				{id:5, name: "Maia", age: "17"},
				{id:6, name: "Jenna", age: "26"},
				{id:7, name: "Medha", age: "17"},
				{id:8, name: "Lauren", age: "23"},
				{id:9, name: "Naomi", age: "33"},
				{id:10, name: "Terri", age: "67"},
				{id:11, name: "Mark", age: "87"},
				{id:12, name: "John", age: "17"},
				{id:13, name: "Wendy", age: "17"},
				{id:14, name: "Gabriel", age: "40"},
				{id:15, name: "Ruth", age: "17"},
				{id:16, name: "Marie", age: "17"},
				{id:17, name: "John", age: "65"},
				{id:18, name: "Abby", age: "37"},
				{id:19, name: "Jackson", age: "47"},
				{id:20, name: "Jacques", age: "19"},
				{id:21, name: "Omar", age: "27"},
				{id:22, name: "Eddie", age: "59"},
				{id:23, name: "Lela", age: "44"},
				{id:24, name: "Leila", age: "28"},
				{id:25, name: "John", age: "55"},
				{id:26, name: "Ana", age: "17"},
				{id:27, name: "Paul", age: "45"},
				{id:28, name: "Amanda", age: "17"},
				{id:29, name: "Farrell", age: "45"},
				{id:30, name: "Sally", age: "18"},
				{id:31, name: "Samantha", age: "19"},
				{id:32, name: "Scarlett", age: "21"},
				{id:33, name: "Scott", age: "69"},
				{id:34, name: "Sebastian", age: "52"},
				{id:35, name: "Madison", age: "29"},
				{id:36, name: "Maria", age: "17"},
				{id:37, name: "John", age: "87"},
				{id:38, name: "Lawton", age: "17"},
				{id:39, name: "Marie", age: "33"},
				{id:40, name: "Layne", age: "17"},
				{id:41, name: "Laurence", age: "17"},
				{id:42, name: "Marina", age: "44"},
				{id:43, name: "John", age: "38"},
				{id:44, name: "Tammy", age: "33"},
				{id:45, name: "Quinn", age: "29"},
				{id:46, name: "Martha", age: "31"},
				{id:47, name: "Laurie", age: "24"},
				{id:48, name: "John", age: "48"},
				{id:49, name: "Lazaro", age: "29"},
				{id:50, name: "Leonard", age: "22"}]
}]);